version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: develop.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_LOCAL_URL: mongodb://mongo:27017/denizpazs
    depends_on:
      - mongo
    networks:
      - asgard

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - asgard

networks:
  asgard:
    external: true

volumes:
  data:
    driver: local
