version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: develop.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    restart: always
    volumes:
      - ./:/app/
      - /app/node_modules
      - /app/.next
    ports:
      - "${PORT}:${PORT}"
    environment:
      DB_LOCAL_URL: mongodb://mongo:27017/denizpaz
    depends_on:
      - mongo
    networks:
      - MONGO

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
    ports:
      - "27017:27017"
    networks:
      - MONGO

networks:
  MONGO:
    name: MONGO

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG