version: "3.8"
services:
  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx/conf.d:/etc/nginx
  #     - ./nginx/certs:/etc/ssl/private
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"
  #   restart: always

  web:
    build: .
    volumes:
      - .:/usr/src/app
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
      - asgard

  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"
    networks:
      - asgard

networks:
  asgard:
    ipam:
      driver: default