version: "3.8"
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/public
    command: npm run launch
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_LOCAL_URL: mongodb://mongo:27017/denizpazs
    depends_on:
      - mongo
    networks:
      - asgard

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
    networks:
      - asgard

networks:
  asgard:
    ipam:
      driver: default

volumes:
  data:
